### ISSUE TITLE
[Story] Block user

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1106]
As a user I want to be able to block an other user so that I don't get annoyed by her anymore.

If https://github.com/vector-im/element-meta/issues/1105 is done show an option to block a user.
Show a hint if the user really wants to block that user.
Don't show on my own profile. I cannot block myself.
 

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Android
- [x] Implementation
- [ ] https://github.com/vector-im/element-x-android/issues/846
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

```[tasklist]
### iOS
- [x] Implementation
- [ ] https://github.com/vector-im/element-x-ios/issues/910
- [ ] https://github.com/vector-im/element-x-ios/issues/911
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

**Comment by amshakal** [comment]
1. Should we have an option to unblock the user? In case it was done by mistake
2. Should we have a place in settings where all blocked users live?
3. Should blocked users be removed from All Chats?
4. Should we allow the user to go into timeline of their 1:1 chat with the blocked user?

**Comment by amshakal** [comment]
Link to figma:
iOS: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=890%3A77602&t=SALHRUFolhzz51OP-1

Android: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1447%3A82661&t=SALHRUFolhzz51OP-1

**Comment by manuroe** [comment]
@kittykat: iOS is ready for QA

**Comment by ghost** [comment]
I have finished testing on an iPhone 12 mini with Element X 1.1.0 (181) via Testflight.

Of the acceptance criteria in Figma, here is what works and does not (working items in **bold**):

- **I do not see messages from that user anymore** 
- **I cannot write in a dm with them**
- **All messages by that person are hidden**
- I cannot invite that person to that room
- We can both be invited to a room by others
- If we are the only people left in a room it should not be possible to write messages in that room

More specifically, here is what I tested and what I saw:
- I cannot tap on a user name or avatar to open the user profile screen (this works in legacy Element). Instead I have to tap the room title, tap _people_ and then tap on the user from there.
- I am presented with an explanatory pop-up when tapping _Block_ from the user profile
- I am not presented with an option to block when viewing my own user profile
- I can cancel blocking from the explanatory pop-up
- I can block from the explanatory pop-up
- When blocking, that user's messages disappear from my view of the room
- When blocking, that user can still see my messages in the room
- When we are the only two people in a room and I have that user blocked, I can still send messages into the room. There is no message at the bottom, "You won’t be able to receive or send any messages until you unblock them" as indicated in Figma mockups.
- I can go back in to the user profile screen and unblock that user
- When unblocking, I can see the user's messages again
- When unblocking, legacy Element prompts me to re-sync. Element X does not prompt me to resync but the messages are there all the same
- I can reblock a user and their messages disappear
- File attachments, pictures, videos and emojis sent by a blocked user display and are able to be interacted with after unblocking that user

I am assuming some of the issues I encountered are due to user flows not being fully implemented yet in Element X (invites for example). Please let me know if any of the above is an issue that I should report, or if you'd like me to repeat or do other testing. For now, going off the Figma designs **this does not pass QA on iOS** because it does not meet acceptance criteria.

**Comment by jmartinesp** [comment]
@kittykat & @ashughes1, this should be ready to test on Android too. It should be included in the latest nightly.

Also, about this:

> If we are the only people left in a room it should not be possible to write messages in that room

I think that was delayed until we implemented powerlevels too?

**Comment by Velin92** [comment]
> I cannot tap on a user name or avatar to open the user profile screen (this works in legacy Element). Instead I have to tap the room title, tap people and then tap on the user from there.

@VolkerJunginger we don't have this behaviour yet, maybe we should have a specific story for it?

> When we are the only two people in a room and I have that user blocked, I can still send messages into the room. There is no message at the bottom, "You won’t be able to receive or send any messages until you unblock them" as indicated in Figma mockups.

Same for this one , we should have a specific story for it, since we need to block the composer

**Comment by kittykat** [comment]
First point is fixed, second one has a user story here: #1786

**Comment by manuroe** [comment]
@kittykat. Given we will do https://github.com/vector-im/element-meta/issues/1786#issuecomment-1624928041 later, can we tick the QA check boxes?

**Comment by kittykat** [comment]
@manuroe We currently have https://github.com/vector-im/element-x-ios/issues/910 and https://github.com/vector-im/element-x-ios/issues/911 that need to be fixed

**Comment by kittykat** [comment]
Closing with known issue vector-im/element-x-ios#911 which is scheduled
