### ISSUE TITLE
[Story] Show a special indicator for mentions and replies in the room-list

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1144]
As a user that has been mentioned in a room or got a reply on a message I want to have a special visibility for these events so that I can act fast.
- Show Show a special indicator for mentions and replies in the room-list.

@UX
-Do we want that at all? I haven't really understood this behaviour in the past (until someone explained it to me...)
## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Tasklist
- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by giomfo** [comment]
@kittykat I think this story is a dup of [this one](https://github.com/vector-im/element-meta/issues/1746)

This story is focused on the room decoration for the mention use case, which is supposed to be handled by the existing one.

I highlight here the replies handling will depend on the intentional mentions implementation, for the point described [here](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/3952-intentional-mentions.md#impact-on-replies). This MSC (Intentional mentions) has been already implemented at the Rust SDK level to handle correctly the pushes. But, if I'm correct, the suggested implementation about replies has not been implemented in ElementX yet. The reply to one of my message will not be detected as a mention for the moment.

Suggestion: close this Epic, create a new one on Replies (I did some tests, the current implementation is similar to the legacy mobile client one, which is buggy (edition/redaction are not applied on related events display). For my point of view, the implementation of the replies (sending and rendering) has to be considered again by including the intentional mentions support

**Comment by kittykat** [comment]
@giomfo Happy for you to do that :+1:

**Comment by giomfo** [comment]
I will close this Epic (a part of the work has been done by https://github.com/vector-im/element-meta/issues/1746)
@VolkerJunginger I let you create a new one if something is missing in EX about the replies
