### ISSUE TITLE
[Story] 1:1 Chat detail page (DMs)

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1167]
As a user I want to access the detail page for 1:1 chat so that I can get some info and modify settings.

A 1:1 chat has ALL of  the following attributes
- The dm flag is true
- There are exact two room members
- The chat is E2E encrypted

The following behaviour is expected from a 1:1 chat:
- The room-name & avatar is the one of the conversation partner
- No other user can be invited to the conversation
- The conversation never ends
- If a user deletes the 1:1 chat it is just deleting the history for himself. The other user can still  write a message in that 1:1 chat.

Implement the following features:

Feature | 1:1 Chat Details
-- | --
Show Avatar | userpic
Show Name | username
Matrix-ID | yes
Room Description / Topic | "notes"
→ Encryption: | Info 
Block User | yes

</div></b>

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Android
- [x] Implementation
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

```[tasklist]
### iOS
- [x] Implementation
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by amshakal** [comment]
Design will first work on features being implemented right now and then focus on the rest of the features as additional info might be needed for each and every one of them. eg. scope of audio/video call has not been defined yet, we don't know what encryption and verify user flow will look like based on what crypto team plans on doing etc.

Additionally slightly worried to have search here. Timeline might be a better place to search for messages.

**Comment by amshakal** [comment]
Are we sure we can and want to do links as well?

**Comment by amshakal** [comment]
Link to Figma, based on future features and requirements:

iOS: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1574%3A87113&t=ZXsZIHrbrFYWRErj-1
Android: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1777%3A94347&t=ZXsZIHrbrFYWRErj-1

**Comment by manuroe** [comment]
@kittykat: iOS is ready for QA

**Comment by jmartinesp** [comment]
@amshakal  @kittykat @VolkerJunginger this is ready to be tested on Android, it should be included in the latest nightly.

**Comment by ghost** [comment]
Testing this on iOS with Element X 1.1.0 (200), I am not sure how to start a DM from Element X itself. I am able to invite myself to a two person room (myself and a test account) using Element Web or one of the Element legacy apps. Not sure that's the same thing as a DM though. I assume it's not the same thing since the details view in Element X on my iPhone 12 mini look very different than the designs in Figma, but here are my results from testing that out anyway.

A 1:1 chat has ALL of the following attributes:
:question: The dm flag is true - _not sure how to check this_
:heavy_check_mark: There are exact two room members
:heavy_check_mark: The chat is E2E encrypted

The following behaviour is expected from a 1:1 chat:
:heavy_check_mark: The room-name is the one of the conversation partner
:x: The room-avatar is the one of the conversation partner - _room avatar is the same as my avatar_
:question: No other user can be invited to the conversation - _I can invite a user to the room from outside Element X (eg. Web, legacy, etc)_
:question: The conversation never ends - _I am not sure what this means_
:question: If a user deletes the 1:1 chat it is just deleting the history for himself. The other user can still write a message in that 1:1 chat. - _I am not sure what is meant by **delete** in this context. I can leave the room or delete individual messages, but I'm not sure how to delete all chats as described._

**Comment by Velin92** [comment]
> Testing this on iOS with Element X 1.1.0 (200), I am not sure how to start a DM from Element X itself. I am able to invite myself to a two person room (myself and a test account) using Element Web or one of the Element legacy apps. Not sure that's the same thing as a DM though. I assume it's not the same thing since the details view in Element X on my iPhone 12 mini look very different than the designs in Figma, but here are my results from testing that out anyway.
> 
> A 1:1 chat has ALL of the following attributes: ❓ The dm flag is true - _not sure how to check this_ ✔️ There are exact two room members ✔️ The chat is E2E encrypted
> 
> The following behaviour is expected from a 1:1 chat: ✔️ The room-name is the one of the conversation partner ❌ The room-avatar is the one of the conversation partner - _room avatar is the same as my avatar_ ❓ No other user can be invited to the conversation - _I can invite a user to the room from outside Element X (eg. Web, legacy, etc)_ ❓ The conversation never ends - _I am not sure what this means_ ❓ If a user deletes the 1:1 chat it is just deleting the history for himself. The other user can still write a message in that 1:1 chat. - _I am not sure what is meant by **delete** in this context. I can leave the room or delete individual messages, but I'm not sure how to delete all chats as described._

@ashughes1 

You can check the `direct` flag from element web in the settings of the room for now (there is no way yet to do that in El-X)

 -Also a DM room, is essentially a room that is started by using the `Start Chat` (on El-Web since there is no invitation implemented yet fully in El-X) option and selecting a user instead of creating a room and inviting people.
- Also the avatar of the user is the one that should be seen in the Details screen (for now we can't show it in the room list yet @VolkerJunginger  but we should actually make a story for this)
- Yes you can invite the users from outside El-X in a DM room, but that would change the DM room into a normal room. The important thing is that is not possible in El-X
- I imagine the last two points mean that in El-X you can NOT leave the room however this is another point for discussion, since I am not sure if we should make DM non leavable.

**Comment by ghost** [comment]
Retested this on Element X iOS 1.1.8 (270) and Element X Android 0.1.0-nightly (July 1, 2023). It seems to be working in line with the acceptance criteria above. Removing this from my backlog, but please tag me if you need something tested.

**Comment by VolkerJunginger** [comment]
Even if we wanted to have a "topic" section for DMs we should remove this now for 1:1 chats in Android. We should not enable users to change the Room name and avatars in 1:1 conversations.
