### ISSUE TITLE
[Story] Send a file

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1185]
As a user I want to send a file so that I can share it with an other user.

- The user should start the file sharing flow from the composer
- The user should be able to pick a file from the file-system on their phone
- A preview is shown to the user 
  - Start w. pictures and pdf; Show a generic icon for all other files
~The user can add a text that is send with the file~
- If the file is an image it should not be compressed. The file should be send as it is.

**Open Questions**
- There is a limit of ? MB for a file
- Any filetype is allowed to be shared

Think about when to start uploading. It could make the app appear faster if the client would start the upload as soon as the file has been picked and then "confirmed" once the user hits send. In other cases the uploading would be stoped and the server would get a signal to delete what has been uploaded. 

- [x] Design signoff
- [x] QA signoff
- [x] Product signoff

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by amshakal** [comment]
I think we discussed that for MVP we might be able to add text along with the file/image. Keeping that in mind, here are the designs.
[File uploading on iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=2285%3A115603&t=9qgQvDswgzKRZpna-1)
[File uploading on Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=2368%3A115883&t=9qgQvDswgzKRZpna-1)

**Comment by ghost** [comment]
Tested this on Element X iOS 1.2.1 (280) and Element X Android 0.1.0-nightly (July 11, 2023). I found some issues (noted below), otherwise please see further below for a matrix of what was tested and the results. I should note that I have not checked for compression of images/video and I did not test file size limitations.

I am leaving this as QA in progress for now and holding off giving sign-off until what I've reported here has been reviewed.

#### Issues
| Issue | Description | Screenshot |
| :---: | :--- | --- |
| 1 | Attachment renders as a pill with a mime-type appropriate icon, the filename, file type, file size, and time sent when a preview cannot be rendered. Based on the requirements above I would have expected this not be the case with a PDF. I've not yet filed a GH issue for this and will wait for confirmation if this is intended behaviour. | n/a |
| 2 | I get an error uploading attachment (see [rageshake](https://github.com/vector-im/element-x-android-rageshakes/issues/184)) when trying to attach an MP3 (first screenshot). <br /><br /> It works on iOS, however if the recipient is on Element X Android it renders an _Unsupported event_ in the timeline (second screenshot). | <img src="https://github.com/vector-im/element-meta/assets/766595/009723a2-247e-4106-a60c-357503fe4c4f" /> <br /> <img src="https://github.com/vector-im/element-meta/assets/766595/30a5decd-d182-46b7-98fa-6ac38b2e912d" /> |
| 3 | On iOS, when replying to certain attachment events the icon renders as an audio graph instead of a file icon ([rageshake](https://github.com/vector-im/element-x-ios-rageshakes/issues/605)) | <img src="https://github.com/vector-im/element-meta/assets/766595/f6cefc28-969d-4b36-82c2-76a847172bcd" /> |
| 4 | I cannot include message along with an attachment. On both Android and iOS there doesn't seem to be UI implemented to include a message. If I start to type a message in the composer and then go through the flow to attach a file my message is not sent, only the attachment is posted. Kat mentioned this needs an MSC to be implemented for supporting this functionality, but I thought I'd call it out since it is expressed in the acceptance criteria above. | n/a |
| 5 | I cannot select multiple photos to upload in a single message on either iOS or Android, this option simply isn't presented so I assume we'll need a user story for that. | n/a |

#### Android (Google Pixel 6a)
| File Type | Attach/Upload | Timeline Preview | Preview is Interactive | Download/Share from Timeline | Message with attachment
| :----------------------- | :---: | :---: | :---: | :---: | :---: |
| Photo from library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :warning: <sup>4</sup> |
| Video from library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :warning: <sup>4</sup> |
| PDF from library | :heavy_check_mark: | :warning: <sup>1</sup> | :heavy_check_mark: | :heavy_check_mark: | :warning: <sup>4</sup> |
| DOCX from library | :heavy_check_mark: | :warning: <sup>1</sup> | :warning: <sup>1</sup> | :heavy_check_mark: | :warning: <sup>4</sup> |
| TXT from library | :heavy_check_mark: | :warning: <sup>1</sup> | :warning: <sup>1</sup> | :heavy_check_mark: | :warning: <sup>4</sup> |
| Photo from camera | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :warning: <sup>4</sup> |
| Video from camera | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :warning: <sup>4</sup> |
| Audio from library | :x: <sup>2</sup> | could not test | could not test | could not test | could not test | could not test |
| **File Type** | **React** | **Reply & Forward** | **Copy & Paste** | **Remove** | **Attach Multiple** |
| Photo from library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| Video from library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| PDF from library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| DOCX from library | :heavy_check_mark: |:heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| TXT from library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| Photo from camera | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| Video from camera | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| Audio from library | could not test | could not test | could not test | could not test | could not test | could not test |

#### iOS (Apple iPhone 12 Mini)
| File Type | Attach/Upload | Timeline Preview | Preview is Interactive | Download/Share from Timeline | Message with attachment
| :----------------------- | :---: | :---: | :---: | :---: | :---: |
| Photo from library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :warning: <sup>4</sup> |
| Video from library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :warning: <sup>4</sup> |
| PDF from library | :heavy_check_mark: | :warning: <sup>1</sup> | :heavy_check_mark: | :heavy_check_mark: | :warning: <sup>4</sup> |
| DOCX from library | :heavy_check_mark: | :warning: <sup>1</sup> | :warning: <sup>1</sup> | :heavy_check_mark: | :warning: <sup>4</sup> |
| TXT from library | :heavy_check_mark: | :warning: <sup>1</sup> | :warning: <sup>1</sup> | :heavy_check_mark: | :warning: <sup>4</sup> |
| Photo from camera | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :warning: <sup>4</sup> |
| Video from camera | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :warning: <sup>4</sup> |
| Audio from library | :heavy_check_mark: | :warning: <sup>1</sup> | :heavy_check_mark: | :heavy_check_mark: | :warning: <sup>4</sup> |
| **File Type** | **React** | **Reply & Forward** | **Copy & Paste** | **Remove** | **Attach Multiple** |
| Photo from library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| Video from library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| PDF from library | :heavy_check_mark: | :warning: <sup>3</sup> | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| DOCX from library | :heavy_check_mark: | :warning: <sup>3</sup> | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| TXT from library | :heavy_check_mark: | :warning: <sup>3</sup> | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| Photo from camera | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| Video from camera | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |
| Audio from library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: <sup>5</sup> |

**Comment by toger5** [comment]
what about mutiple photo selection. Is this not planned for the inital implementation. (I think that is super important)

**Comment by kittykat** [comment]
> what about mutiple photo selection. Is this not planned for the inital implementation. (I think that is super important)

Not for the initial epic, we will have an issue for followup :+1:

**Comment by ghost** [comment]
The multiple images/video case has been filed here:
https://github.com/vector-im/element-meta/issues/1866

**Comment by kittykat** [comment]
All blocking issues resolved and open issues are not blockers
