### ISSUE TITLE
Change default notif volume for non-1:1s

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-meta#1359]
All my notifs are turned up way too high. I suspect we should not notify for any message in group rooms by default. To fix up existing rooms we need a way of bulk editing notif levels really. This overlaps a bit with 'night mode' style presets for setting alternative notif levels

**Comment by ara4n** [comment]
Notification volume control is basically a mess full stop right now:
 * The master overrides in UserSettings (e.g. "turn group chat notifs to 'off'") are not reflected whatsoever in the volume context menu for that room.  We can't even tell if they're overrides or not!
 * People can't find that menu anyway (plus it should be merged with the general avatar menu rather than hiding two of them there: vector-im/element-web#3013)
 * We don't show the current volume state of the room in RoomTiles in RoomList (#3346)
 * The volume control refers to the 'noisy' setting as 'loud' rather than 'noisy'.
 * ...and there's no way to bulk-edit rooms anyway, short of the confusing radio-button overrides in UserSettings.

So, what shall we do?  After brainstorming with @lukebarnard1:
 * [x] Merge 'tag' & volume control context menus together (https://github.com/vector-im/riot-web/issues/3013).  Let's put the volume on top and 'tag' below with a horizontal separator in between like the tag menu has already
 * [x] Fix the label to be 'noisy' rather than 'loud'
 * [ ] If the room volume has been overridden by the radio buttons in UserSettings, grey out the selector or replace it with a "set to noisy in _Settings_" label (with a link through to User Settings"?  Assuming it overrides at all?
 * [ ] Create a UnkDevDialog style Dialog which you get at from advanced settings for notifications in UserSettings, which:
   * [ ] Table, listing all the rooms
   * [ ] Dropdown (`<select/>`) per room to select between mute / mentions-only / normal / noisy
   * [ ] Checkbox on LHS to allow bulk-selection for bulk-operations, using a bulk assign dropdown (similar to the GH Issues one)
   * [ ] Allow shift-clicks to bulk-select subsets of the checkboxes.

Stuff we're descoping from this:
 * Putting the volume control on the RoomTile (#3346)
 * "Night mode" style presets (#1672), although in future we'd expect to use the new dialog for managing that.

**Comment by daniellekirkwood** [comment]
I'm going to close this issue but also link it to the related discussion here: [#1595](https://github.com/vector-im/element-meta/discussions/1595?converting=1)

We're in the process of simplifying notifications across all of our platforms and the current decision is to _not_ make any changes to the defaults for new users based on room type. Just because a room has several people in it, we do not think that we're currently intelligent enough to make this decision on behalf of users. Having said that, there is likely a future where this is a great path for us to take (hence keeping the discussion, comments and feedback in Discussions).

We are taking other steps to make notifications easier to manage (these are all being tracked elsewhere) and include, but not limited to: 
- simplifying the settings page: we believe if settings are easier to change _not_ defaulting different settings for different room types is easier to manage for new users
- making the quick settings for a room easier to access, change, and grok
- making the notifications settings of a room clear when you join it with 'point of need information' (see draft design)
- adding smart banners so if we believe someone has the 'wrong' setting, we can suggest that they change it (see draft design)
- others... 

Smart banners:
<img width="590" alt="Screenshot 2023-05-12 at 11 52 02" src="https://github.com/vector-im/element-meta/assets/89144281/905f5502-7739-466b-8f0e-e3babfae2082">

<img width="590" alt="Screenshot 2023-05-12 at 11 52 15" src="https://github.com/vector-im/element-meta/assets/89144281/315d1129-a8bc-41d3-b3e9-46e495994220">

Point of need:
<img width="365" alt="Screenshot 2023-05-12 at 11 58 03" src="https://github.com/vector-im/element-meta/assets/89144281/14728537-a6aa-4182-b70a-9971a9afc853">
