### ISSUE TITLE
We should use our blog more (for releases)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-meta#1416]
Synapse publishes a blog post every patch release, and we should probably do the same. It would at least help ensure the information sent to the announcements room and twitter is consistent and helpful, rather than an occasional mismatch leaving people questioning things

**Comment by daniellekirkwood** [comment]
This issue is 2 years old - I don't think it's still relevant so I'll close it out.
Today we have: a marketing team who handle the blog posts and PMs who help to write posts and update our audiences. TWIM should also reflect release note style changes.... and each platform has their releases notes in GH. 

If there's desire to do more, let's chat about it/raise a new issue :)
