### ISSUE TITLE
Coherent names for passwords.

### ISSUE THREAD

**Issue by gitvalds** [vector-im/element-meta#1474]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

During the login, using Firefox, I was asked for the "security phrase".
I always save these passwords with the name that they are called by Riot.
There was no such thing.
So I had no alternatives than to try all of my passwords, which is risky because I am giving them all to the server and maybe to others.
The correct name this time was "recovery passphrase".
So now I have written in my notes "recovery passphrase, AKA security phrase".
This happened in the past with different names.
Here are them all.
I have no idea what they are used for, so they are just in alphabetical order.

encryption key
key backup
recovery passphrase
recovery password
recovery key
security phrase

### Steps to reproduce

It happened when I was logging in.

Logs being sent: no

### Version information
platform: web
Firefox 78.0.1 (64-bit)
Fedora 32

**Comment by ell1e** [comment]
I already mentioned this in vector-im/element-meta#1523 , but all these names once made coherent also really should be mentioned in https://about.riot.im/help#end-to-end-encryption with at minimum the following info: 1. what exactly does each one do, 2. how exactly can each one be changed/reset/recovered (or not), 3. what is the consequence of each one being obtained or guessed by some attacker, 4. which one is stored server-side under which circumstances (e.g. with key backup enabled)

**Comment by richvdh** [comment]
Recovery passphrase was renamed (in the UI, at least) to "Security phrase".
Recovery key was renamed to "Security key".

(It's slightly more complicated than that, because previously the recovery phrase/key was only used for server-side backup encryption, whereas it is now used for the more general server-side secret storage, which itself is used to store a recovery key for a key backup. But the migration was supposed to be relatively seamless, and the thing you previously used as a recovery phrase/key can now be used as a security phrase/key).

Please file platform-specific issues highlighting any parts of the UI you see using the old terms.
