### ISSUE TITLE
Have different default notification level for room vs discussion

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/element-meta#1568]
- **Browser**: Firefox 64.0.2
- **OS**: Fedora, macOS

### Description

By default the notification seems to be set to "All messages". After a small discussion on [#linear-supporters:matrix.org](https://matrix.to/#/!eUGMvloIjhBoAwlyRh:matrix.org/$1548786068122372JJRUF:matrix.org?via=matrix.org&via=kittenface.studio&via=kolosowscy.pl), we thought it would be interesting to have it set to "Mentions only" by default for rooms and "All messages" for discussions.

The rational is that on rooms there are often several people talking together and having a notification each time there's a new line can be upsetting (experienced by my less tech-savvy friends and family who removed Riot notifications altogether either in the apps config or directly on their phone).

My use case is that if I want the attention of someone in a room, I mention him, and my friends tends to do the same as well. But for discussion rooms, I use them as a replacement for my SMS now, so I need a notification each time there's a new message.

### Steps to reproduce

- Create a new room
- See that the default notification level is set to "All messages"

- See that it's also the case for discussion room

**Comment by daniellekirkwood** [comment]
This issue is a duplicate of this: https://github.com/vector-im/element-meta/issues/614

However, it's interesting feedback that we may like to revisit in the future when Notifications in Element and EX have been simplified. Therefore, I will move this to the discussions so that we can continue to collect feedback and revisit our decision _not_ to action this in the future.

Thank you for your understanding.
