### ISSUE TITLE
Clean up Composer actions

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2307]
### Your use case

Please reorder the actions in the composer so they make sense:

New sorting (top to bottom)
- Camera (its more like that people take a picture to send than picking from their (often private) galerie)
- Photo & video
- Attachment
- Location
- Poll
- Text formatting

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2803
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2790
```

**Comment by amshakal** [comment]
Happy with the order you mentioned. I personally dont have a strong aversion towards either and can see pros and cons in both. So we can stick to top to bottom for now.

**Comment by VolkerJunginger** [comment]
Edited the ticket!

**Comment by jmartinesp** [comment]
Just to mention it: Android has separate 'Take photo' and 'Record video' actions because the OS won't give us a joint version where the user can do one or the other. I guess we just need move both to the top of the list.

**Comment by bmarty** [comment]
> its more like that people take a picture to send than picking from their (often private) galerie

My 2 cents: I never use the Camera directly from any application to share a photo, but always pick a image from my gallery. The reason is that I want to have the photo in my gallery (for posterity), and then I can eventually share it using  multiple applications.

Do you have some analytics to make this assertion?

**Comment by VolkerJunginger** [comment]
My 2 cents: I am using the camera quite often ;)

Plus: This is often a "work-place" app running on a private device. I know from my past job where we did a lot of user testing that users did not like having work related pictures in their private picture gallery.

AND I think grouping the actions for the same feature (sending a picture) is something  we
a) see with other messengers
b) [makes sense ](https://www.nngroup.com/articles/common-region/#:~:text=Definition%3A%20The%20principle%20of%20common,some%20common%20characteristic%20or%20functionality.)

**Comment by ara4n** [comment]
as per https://github.com/element-hq/element-x-ios/issues/1487 i am super unsure that putting the most common items as far away from the button as possible is ergonomic. Obviously in general you put the most important things first (reading top to bottom), but in terms of building up spatial memory and minimising needless movement and improving accuracy of selection, i would strongly expect the most commonly accessed operations to be closest to the button used to trigger them. iMessage gets it wrong imo, and it jars every time.

**Comment by VolkerJunginger** [comment]
![thump zones](https://github.com/element-hq/element-meta/assets/118339066/a0f9c1c4-0cb0-4dfe-a93d-4dfa5f2c0e3f)

I don't agree. As you see w. my image attached when sending a picture or any other non-text message the buttons are highly accessible. When sending a text message the option to format the text is.

As you cannot send an image w. text on Element I think optimising the UX for the user-flows this way is a good compromise. Even worse: turning it upside down would put the formatting in a bad position when writing a text.

btw. I think the alternatives from iMessage (using an overlay and making sure the buttons are always at the same position) or the way WA is doing it now is also a  good alternative as it makes sure that the UX not affected to much by bigger screen-sizes.

**Comment by rwjack** [comment]
What about having 2 action buttons? 

A camera button that opens up a list of recent gallery images, the first "image item" being the camera, allowing the user to take a picture and send it directly, or otherwise select multiple images from that list to send.

And the second button being the "+", with the rest of the items, attachment, location, formatting...

OR ideally, use a single "+" action button with the gallery explained above, have a few small buttons inside for attachment, location, poll, and figure out something else for the formatting, e.g. long press the composer text.
