### ISSUE TITLE
[Prep] Developer option to override SS proxy URL

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2468]
### Description

It is going to be used by the backend team for testing the native implementation of SS.

# Acceptance criteria
- The user can define the SS proxy URL in developer options
- A required restart is fine

# Size estimate
S

# Dependencies    
- None

# Out of scope
- 

# Subtasks
```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/pull/3164
```

```[tasklist]
### iOS
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

**Comment by erikjohnston** [comment]
This is so that we can see how well the new backend API works (without having to do changes to the client side). This should hopefully help iron out bugs and performance problems etc. In future, the Rust SDK will include changes that require the new API, and it would be good to be able to use this same mechanism to test that.

Having a way of overriding the SS URL will work well for this I think, though hardcoding the new endpoint (at `/_matrix/client/unstable/org.matrix.simplified_msc3575/sync`) would also work, in case that is easier. We also don't mind (on Backend side) if this is a different build from the standard EX (again, if that is easier, especially if in future we need to incorporate Rust SDK changes).

**Comment by manuroe** [comment]
@erikjohnston is this still required? 

We discoverd a major [issue](https://github.com/element-hq/element-x-android/pull/3164#issuecomment-2217227158) when implemting it. It would require significant efforts to make it.

**Comment by erikjohnston** [comment]
@manuroe I think that the SSS toggle in the nightly apps now cover the use case we were after (testing the new APIs with the real apps)
