### ISSUE TITLE
Invisible Crypto: EX Android: display a warning when an *unverified* user changes identity

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-meta#2524]
Followup to https://github.com/element-hq/element-meta/issues/2492.  Part of https://github.com/element-hq/element-meta/issues/2491, itself part of [Invisible crypto](https://github.com/element-hq/crypto-internal/issues/282).

When an unverified user changes their identity, we need to make our user aware of this. In the long term, the intention is just to show a notice in the timeline (#2493); however, that is difficult to implement and we need a stop-gap.

This task is for Element X Android.

The proposal is to show a warning above the composer, in much the same way as we would for *verified* users (#2491), but without locking the composer.

Figma designs:

* [EXA](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=340-33999&t=S7GYP1iJFJMzIRid-0): 

![Image](https://github.com/user-attachments/assets/2343f21f-6527-4b52-91b3-3d6876fac16c)

**Comment by mxandreas** [comment]
For visibility: https://github.com/element-hq/element-meta/issues/2525#issuecomment-2394051527

**Comment by manuroe** [comment]
@bmarty can we close this issue thanks to https://github.com/element-hq/element-x-android/pull/3621?

**Comment by bmarty** [comment]
Yes, indeed, this is done in https://github.com/element-hq/element-x-android/pull/3621

> This task is for Element X Android.

@andybalaam for next time, can you create the task to the EXA project https://github.com/element-hq/element-x-android please? The created issues can then be added to the story, https://github.com/element-hq/element-meta/issues/2544 in this case. The story was in the correct project element-meta. Thanks!

This also apply to https://github.com/element-hq/element-meta/issues/2525 which should have been created on the EXI project https://github.com/element-hq/element-x-ios.

It will reduce confusion since I see that comments have been added to the iOS task and not to the story, for instance this one: https://github.com/element-hq/element-meta/issues/2525#issuecomment-2397334986. CC @mxandreas.

Thanks all!

**Comment by andybalaam** [comment]
> @andybalaam for next time, can you create the task to the EXA project

Thanks for the heads up. We actually recently changed our processes so future tasks should be in the correct project. Sorry for the time-waste this time.

Thanks!
