### ISSUE TITLE
[Story] Show in the UX if a user is verified

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#2532]
### Description

* As a  User
* I want to see when a user has been verified
* So that I know that the communication channel is authentic beyond doubt

### Acceptance criteria

If I haved verified another user using another client (Web), I should see the verified mark on that user avatar. (everywhere the user avatar is shown?)

<img width="171" alt="image" src="https://github.com/user-attachments/assets/091273e8-ff71-4d42-b2aa-a4493d0fff52">

Verifying another user from EX is not in the scope of this issue.

### Leads

* Tech: <GitHub id>
* Design: <GitHub id>

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by mxandreas** [comment]
Perhaps clarify that while we do not plan to implement the verification process on EX, we want the "verification badge" to be shown consistently on EW and EX which means we have to let Aaron to think through how to do it - since EW already has a way to show it, but it is not exactly "on the avatar" there as well.

I think this is not something that is worth keeping track of it but rather do at the end of the invisible crypto track. I do not think it will cause much friction at the moment if it is missing on EX.

**Comment by andybalaam** [comment]
Waiting for design on this and a "how to verify" help button of some kind.

**Comment by mxandreas** [comment]
We agreed that for now we show it just in the profile of the user on EX, and since latter is part of https://github.com/element-hq/element-internal/issues/640 and will be done very soon, I think we can close this.

@BillCarsonFr you also brought up that on EW the approach we currently use to show someone is verified, is not super clear or consistent. I am happy to capture this problem on the roadmap so we would not forget about this, but it is clear that it is something that will be postponed to later.

**Comment by andybalaam** [comment]
The minimal solution is being implemented in Element X ( https://github.com/element-hq/element-internal/issues/640 ), so closing this one.
