### ISSUE TITLE
Do some work on MSC4147

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-meta#2557]
[MSC4147](https://github.com/matrix-org/matrix-spec-proposals/pull/4147)

The work that was planned for it is described at https://github.com/element-hq/crypto-internal/issues/369

**Comment by uhoreg** [comment]
Looking at my own Synapse database, and running the following query:

```sql
select length(message_json) from device_inbox;
```

there seems to be two main clusters of message lengths: one around 1400, and one around 2400.  So it looks like adding the device keys increases the message length by a factor of about 1.7, or by about 1000 bytes.

I'm not sure what other statistics we need to gather.  We could look at matrix.org performance graphs between end-of-June (when the feature was initially implemented in the Rust SDK) and now, but I'd expect them to not be very useful as there would be a lot of factor affecting performance.  So aside from saying that "it hasn't been a disaster on matrix.org", I'm not sure what else we can say.

We could add some logging?  Maybe log how many to-device messages and the total size of the to-device messages are sent per /sync response, along with the total size of the /sync response, to give an idea of how much it's inflating the /sync response size on average?

I'd expect it to not have a huge impact on the speed of the /sync response, since it isn't making any queries any more complicated.  It's increasing the data size, but I don't think that the data transfer is the slow part of the /sync.

**Comment by andybalaam** [comment]
The rest of this is covered by https://github.com/element-hq/crypto-internal/issues/369
