### ISSUE TITLE
Investigate why Element X Android reports higher UTD count (timeboxed to S)

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-meta#2591]
Come up with some ideas about how to investigate the higher UTD counts on Element X Android.

Possibilities:

* Does Android have a different definition of "on screen"?
* Does the fact that Android hold multiple timelines in memory cause this effect?
* Is there a real bug causing more real UTDs?
* others you can think of...

**Comment by BillCarsonFr** [comment]
Some things to look at:

-  https://github.com/element-hq/element-x-ios/issues/2889 
- https://github.com/element-hq/crypto-internal/issues/387

**Comment by toger5** [comment]
Do android x users have a higher chance to also use the legacy android app -> that might affect utd's more than the legacy ios app?

**Comment by BillCarsonFr** [comment]
Scenario to try out:
- Notification client receives a UTD message in background => When is it reported to posthog? Does the app need to be opened?

On iOS, if there is a UTD in the NSE, is it later reported when the app is opened?

**Comment by BillCarsonFr** [comment]
Let's spend 2 days on that now.

**Comment by BillCarsonFr** [comment]
Results of the analysis:
EXI is under reporting and EXA is over reporting.

For EXI to report an UTD you have to be in the room while the event is received. You can leave the room after and it will be reported. But if the timeline is not opened at the time of reception it won't report the UTD.

So if you receive a UTD from a push notif, then you open the app it won't be reported.

EXA is reporting more because the app is keeping a LRU cache of recent timelines (up to 16) so if an event arrives in any of these cached timeline it will be reported. Also for performance reasons when android receives a push notificiation it will also trigger a app sync so that you see the event quicker when opening the app, so there is always a timeline for pushed events.

=> EXA is over reporting because it is reporting UTD that are not visible to users

**Comment by andybalaam** [comment]
> EXA is under reporting and EXI is over reporting.

Should be:

> EXA is OVER reporting and EXI is UNDER reporting

Right?

and 

> ...You can leave the room after and it will be reported...

should be 

> ...You can leave the room after and it will NOT be reported...

right?

**Comment by BillCarsonFr** [comment]
> > EXA is under reporting and EXI is over reporting.
> 
> Should be:
> 
> > EXA is OVER reporting and EXI is UNDER reporting
> 
> Right?
> 
> and
> 
> > ...You can leave the room after and it will be reported...
> 
> should be
> 
> > ...You can leave the room after and it will NOT be reported...
> 
> right?

Fixed the first part, yes `EXA is OVER reporting and EXI is UNDER reporting`

For the second part, it's a bit more complex see this issue https://github.com/matrix-org/matrix-rust-sdk/pull/4252 there is a regression

**Comment by richvdh** [comment]
In recent days, EXA has shown a significant drop in UTDs, bringing it much closer to EXI and EW:

![Image](https://github.com/user-attachments/assets/27aea756-3d27-4f3f-9f3d-d84e2efd1ed1)

The drop appears to coincide with the release of [v25.05.0](https://github.com/element-hq/element-x-android/releases/tag/v25.05.0). We're attributing the drop to https://github.com/element-hq/element-x-android/pull/4561, which means we don't keep timelines in memory for as long.
