### ISSUE TITLE
Let devices request keys to decrypt past history for a room.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-meta#647]
If I'm in a room as device A, and join it later as device B, i need a way to request the old room key data from device A.

Similarly if I'm invited into a room by someone and they want to share past history with me, they need a way of transferring key data.

**Comment by BrenBarn** [comment]
I just read through this whole thread and I still don't understand exactly what the consequences of E2E are or are supposed to be for users.

If it is really the case that simply logging out and logging back in again can cause you to lose access to messages you previously had, that seems absurd.  Logging in and out on the same device shouldn't impact access to messages in any way.  Also, the current messaging from the app on this is not at all clear.  It has some message about "key backup" and then the alternative is "I don't want my encrypted messages".  If it is the case that logging out loses access to messages, the app needs to say that explicitly, something like "WARNING: If you log out you will lose access to encrypted messages!"

Also it is suggested in vector-im/element-meta#1886 that exporting keys and then importing them later won't give access to old messages.  If so, then what is the purpose of exporting the keys?  There needs to be much clearer documentation that tells users "If you do this, you will lose access to such-and-such messages".  Right now I'm somewhat reluctant to log out on any device because nowhere can I find an explicit statement of how to determine what the consequences of that would be.

**Comment by aaronraimist** [comment]
vector-im/element-meta#1886 says they aren’t like GPG keys in that they don’t give you access to *future* messages, not that they don’t give you access to old messages (that’s the only thing they do). Will edit the issue assuming that explanation is clearer.

**Comment by bilbobagginsnz** [comment]
Looking forward to getting this one sorted, thank you GitHub team 🙏🏼⚡️

**Comment by richvdh** [comment]
Didn't this get fixed?

**Comment by pmaier1** [comment]
Can we close this in favor of https://github.com/vector-im/element-meta/issues/749? To my knowledge vector-im/element-web#749 will be the way to go here and we want to schedule it soon(tm).

**Comment by richvdh** [comment]
vector-im/element-web#749 is an epic describing a desired end goal rather than a particular solution, whereas this was more an idea for a particular implementation.

Nevertheless I still think this has been done and should be closed; if anyone disagrees, we can reopen with more context.

**Comment by karolyi** [comment]
Pardon my intrusion but in which version did this get solved? I'm using 1.71 and it still doesn't work there.

**Comment by richvdh** [comment]
> Pardon my intrusion but in which version did this get solved? I'm using 1.71 and it still doesn't work there.

Version 1.71 of what? Note that this is the element bug tracker.

The fix landed in Element Web in https://github.com/matrix-org/matrix-js-sdk/pull/454. You're likely seeing a different problem; feel free to open a new issue and *send bug reports* from both the sender and recipient applications (see also https://github.com/vector-im/element-meta/issues/245)

**Comment by karolyi** [comment]
Oh sorry, the ecosystem around matrix is a bit convoluted. I'm using synapse 1.71 and element-web 1.1.17 and we're still seeing this problem.

**Comment by HarHarLinks** [comment]
Based on the problem statement in OP (without reading the whole thread) and the explanation in https://github.com/vector-im/element-meta/issues/647#issuecomment-1252083744, I don't think this is "solved", merely worked around in one specific setting. To me the wording of both implies that vector-im/element-web#749 duplicates this issue (but is phrased more clearly).

**Comment by JokerGermany** [comment]
Is this issue for such a case?
![encryption problem](https://github.com/element-hq/element-meta/assets/30293477/676dd9ff-1912-4b74-82d5-dfe288d722e1)
Element Desktop session crashed and i cross signed it with another devices.
Since then there a some messages in the "middle" which can't be decrypted.
I looked on another devices and the messages can be read there.
I don't get any message to request the keys from another device

**Comment by uhoreg** [comment]
No, this issue is for getting keys for messages sent while you were not in the room.  For messages sent while you were in the room, and that other devices of yours can decrypt, it should be handled by key backup.

**Comment by jittygitty** [comment]
This issue started in 2016, any update? Is this possible now? I just had another friend want to QUIT using element chat!
He LOST his keys and everything, he does NOT want to install it again without way to regain access to chats!

I was basically in the chats with him, and my user/device should be able to send him keys to decrypt past messages.
I use Element Desktop. Is there a way he can recreate/reset his "user" and then allow me to send him decryption keys?

**Comment by mpeter50** [comment]
jittygitty, I'm really sorry it got to be this long.

> This issue started in 2016, any update? Is this possible now?

As I know it _was_ done in Element web (maybe desktop and android too), in a special way.

When you, from an Element client, invited a user, your client has sent all the keys for past messages (of course only those that it has known) to the invited user. Maybe they also needed to be using a device with an element client, possibly with a version that has implemented support for it. I think [this](https://github.com/uhoreg/matrix-doc/blob/shareable_keys_msc/proposals/3061-shareable-room-keys.md) was the MSC proposal for it.
For when a member of the room has lost the keys, the workaround to send them would be to kick them (or have them leave) and then invite them, and before you say this is silly, it is but there was a reason it worked this way, and it is related to security.

However, the clients since then have switched to the more efficient Rust-based cryptographic library, and this feature was not (yet?) reimplemented there. See the "Sharing room history" heading under "Notes" [here](https://github.com/element-hq/element-meta/issues/2317).
There is a github [issue](https://github.com/matrix-org/matrix-rust-sdk/issues/580) in the Rust SDK repo for implementing the feature, and it is part of the "stabilize the crypto crate" milestone, so it will be done at some point, I guess? It also has a PR with an implementation, but it seems review has been stuck.
Element web also has an issue tracking this, it is [currently waiting](https://github.com/element-hq/element-web/issues/26867#issuecomment-1968797654) for the Rust SDK to implement it.
Last week it was also [mentioned](https://github.com/element-hq/element-x-ios/issues/1496#issuecomment-2188762175) in the Element iOS repo, the comment might shed some light on what is happening.

I would appreciate if an Element employee could tell if this is accurate.

> He LOST his keys and everything, he does NOT want to install it again without way to regain access to chats!

I totally agree that it is very uncomfortable. This is one of the strongest reasons why I don't yet bring people onto this platform, because I know this will bother them, and as it stands now, virtually everyone will experience it at least once.
However, let me tell you how do I look at it.

What is Matrix, when looking at its end to end encrypted rooms?
It is basically a Signal, but with the possibility of logging in on multiple devices (without requiring constant direct connection between them, e.g. at the home LAN like Signal and SimpleX "solves"' this), and even being able to read and send new encrypted messages.
Because of that it is (almost) a Telegram when looking at usability, but with security included. (except client performance, that is nowhere near it..)

So basically, I think Matrix is just more, because it allows more flexibility than Signal.
It is still more even when the encryption fails (safely), because you can still exchange new messages in that room, or participate in unencrypted rooms, or the other ones where encryption still works. In the absolute worst case, when you somehow lose all keys, it just falls back to a little bit **above** the level of Signal, where the keys are only stored on your single phone, and if you somehow lost them, you lost keys to **all** of your messages.

Why is Matrix miserable at implementing this reliably? I think it may be related to the reason why is it that they are the only one doing E2EE with multiple simultaneous logins at all: handling keys in this manner is very hard.
Most of the issues around encryption in Matrix are about keys not being there where they should, because they were lost _somehow_, and theres a million ways that could happen.
- It was lost on client storage, 
- they were not persisted to client storage (because of a crash, killed process, platform crash, power loss or anything at the wrong moment), 
- they were persisted but the client did not have the time needed to upload them to key backup before it was closed, and did/could not send to other devices either for some reason,
- they were lost in transit and not available anymore,
- many other reasons probably

Often this will fix itself because one of your devices has the key, but it is not online to respond to key transfer requests of your other device. At least they dont need to be online at the same time.

But this case is probably not even about a key handling bug that is _that much_ complicated.
How did he lose his keys? Did he uninstall the app, or reset its data from the platform's settings, or what has happened?
Did he set up key backup? Probably not, because the clients do not push that hard enough, and I can imagine the prompt is just dismissed without a though (or is it even shown at all for new people?).
This is not about blaming the victim, but honest questions that need a response, for the problem to be solved or avoided in the future.

You know, when the same thing happened to me and got to learn the lesson, my account was fairly new and I didnt lose much.
But I too was very frustrated when I realized that new members of the encrypted room, not even just cannot read the former messages, they dont even see there are any because the client "helpfully" hides them. Even worse, it was with people I had barely known, I was just organizing a team! And then when they lost their keys because they reinstalled the app, switched phones and didnt use a desktop, or whatever, and werent able to see old messages..
But my point is, that once you understand that it is still a better outcome than what Signal or such could have allowed - because there the same user-stunt would have resulted in _total_ loss of _all_ messages in _all_ chats - it becomes more clear that sometimes the problem is between keyboard and chair. Its a bit like not knowing your google password, wiping your phone, and being surprised that you cant log in to your gmail inbox or install your purchased apps.

Often this is the reason software orgs are afraid from implementing complicated features.
Not just because they lose reputation if it is buggy. But also because if the user doesnt see that doing specific things is dangerous, they will become angry when it does not work as they have expected. And communicating that it does not work that way is very hard, even more if we think about that most users just dismiss any dismissable dialog, and complain if it is not dismissable, but at the same time dont forget that most of the problems are not even coming from pressing buttons in a matrix client, but instead it being affected by its environment: getting suddenly closed and such.
See the situation of Matrix: Signal users mostly understand (I think?) that the messages are stored on their devices, and can conclude that deleting the app without a backup or losing the phone results in total loss of data. On Matrix, users understand that their data is stored on a server, but its not evident that access to part of it depends on a complicated thing called encryption, and that things are needed for it work that are never stored on the homeserver, for the encryption to not be nullified. And in turn, they expect that everything is stored on the server, like with an unencrypted messenger, and they expect that uninstalling the app can not have consequences. When they lose their keys, on next login they still see their old chat rooms and in case of unencrypted rooms even the contents, and they think that its a critical bug that they cant see their encrypted messages.

This got to be very much too long, but it is not a scolding or anything like that, I was just hoping I could give my perspective, in case it helps.
The most important thing about it is that (in my opinion) it must be kept in mind, that in the absolute worst case, you can lose at most as much as on Signal, but when things go wrong its often less. If you were using Signal, your friend would have lost all the messages anyway, probably (probably, because we dont know what caused this).
And also, seeing "unable to decrypt" does not always mean lost keys, but that your device did not have yet received the right keys. Maybe it is on the way among a thousand others and it takes time to process them, maybe the only device holding it has not been online since the request.

For the long term, I very much hope that we will get the possibility to send the keys for former messages to the other members.
I have read spec proposals that vision this happening even automatically, but they said a lot of changes need to be made until that can be done securely.

**Comment by jittygitty** [comment]
mpeter50 thanks for the very detailed write-up. I decided that until the complex crypto is stabilized that I will "only" be using encryption on rooms/chats with users on home servers I do not control. When I use on my own server, I think it makes more sense to simply encrypt the underlying storage via dm-crypt/Luks or other, and as long as everyone in chat is on the same home server, it doesn't seem much benefit to enable encryption at all in such cases, so I won't enable it.

Of course, for federation uses and connecting to home-servers you don't 'fully trust', encryption is "indispensable".

Also, t3chguy replied to me at https://github.com/element-hq/element-meta/issues/245
Anyone know what clients currently make use of https://github.com/matrix-org/matrix-js-sdk/pull/454 ?

**Comment by mcg-matrix** [comment]
> I was basically in the chats with him, and my user/device should be able to send him keys to decrypt past messages. I use Element Desktop. Is there a way he can recreate/reset his "user" and then allow me to send him decryption keys?

You may be able to transfer the keys to your friend in a file:
 1. Create an export of all your keys (to a file on disk); in Element-Desktop this is called "Export E2E room keys".
 2. Extract the keys you want someone else to have (by room id):
     - there's a tool called `megolm_backup.py` that can read the file with the exported keys, see https://github.com/cyphar/matrix-utils;
     - the filtering would be done by piping through something like `jq 'map(select(.room_id == "!herestheroomid:example.org"))'`;
     - and again `megolm_backup.py` for writing the new file with only the extracted keys.
 4. Pass a copy of the file with the extracted keys to your friend using some confidential way (though I believe the keys are protected by a password), e.g. in a Matrix room.
 5. Let your friend import all keys from the file you gave him; in Element-Desktop this feature is called "Import E2E room keys".

Instructions for exporting and importing room keys in various versions of Element: https://ems-docs.element.io/books/element-cloud-documentation/page/export-and-import-e2e-room-keys

**Comment by jittygitty** [comment]
@mcg-matrix Awesome! Thanks for taking the time to share that! I'll try convincing my friend to give it another shot and reinstall element chat, and then will try that!

**Comment by mrlogick** [comment]
I really don't understand. If you are able to export the keys and manually give them to the other user, why can't you just make a simple button?
The user with the past keys should click the button to send the keys to the server (but encrypted). When the other user goes online he gets the past keys from the server (and decrypt them).
On Element there was already a button saying something like "Unable to decrypt message. Request keys...", but for some reason never works.

**Comment by mpeter50** [comment]
> I really don't understand. If you are able to export the keys and manually give them to the other user, why can't you just make a simple button?

I think that would introduce a security vulnerability, backed by social engineering.
To begin with, the reason this is not done automatically is to protect the users from a malicious homeserver. A homeserver admin can add any user to any room (with database editing or modifying the server software), and if this would happen automatically then a new, "forged member" would receive the keys for past messages, nullifyng encryption. Its possible that only a single member would notice this because the server picked him and didnt tell the others, maybe even eradicate the events afterwards.

You suggest this to be done manually, but that has similar issues.
A hostile homeserver could take over your friend's account, or just not deliver his messages to you and instead forge custom messages in his name. By doing this, the admin could convince you to press this button to send him keys for past messages. Again, encryption nullified, because the user does not know better either.

If I can recall correctly, the rationale behind the past workaround (sending the keys to the user being invited by you) was generally that the inviting user (who still has the keys) can verify that he account he is inviting is actually the account of his friend, but I dont remember the specifics.

So to answer your question, this is actually safer because the homeserver operator cant fool you to spill your keys to him. This way you can transfer the keys to your friend "out of band", in a channel of your choosing that is not affected by the adversary, lets say on a pendrive handed over in person, or a shared encrypted cloud storage folder (but still making sure in person that its really them who requested your keys).
Also, exporting the keys is more cumbersome than pressing a handy "send all keys" button, so the user has time to realize that they should do this carefully.

Additionally, even if you believe that you have choosen a homeserver in which you trust, it could get compromised, or even confiscated by adversaries. Probably this does not affect most people, but its always good to be aware of the risks.

On the other hand, sharing your keys this way is risky because if you did not filter the backup correctly, your friend will also receive keys for other messages of yours.

>  On Element there was already a button saying something like "Unable to decrypt message. Request keys...", but for some reason never works.

I think that button just instructs your client to ask all your other logged in devices if they have the keys for that message.

**Comment by jittygitty** [comment]
@mrlogick Actually I was thinking the same. If this works just fine, then I don't see why users can't be given the option. I think the "user is too stupid" mantra is usually taken too far and ends up with oh let's lock out users out of their own $1500 device/phone that they bought, no Admin/root access to users, or they'll uninstall factory spyware? Encryption on phones with modems and baseband/master processors without true isolation, gives a "false" sense of security, agreed?

And so, while I sympathize with the points mpeter50 made in his reply to you, and I'd agree such measures shouldn't be done "automatically or even too easily" such that it could be accidental, a good trade-off 'balance' should be attainable.

I really wanted to try out Kopia soon, and now I want to try bupstash.io also!

But tell me, why force encryption like Kopia also? Why not let us skip it? Sometimes I just don't want encryption and I don't like being 'forced' to use it. It adds more complexity and harder recovery. And isn't it easier to do deduplication, or do it better even (not really sure how dedupe works with encryption), if there's no encryption enabled? Sorry I digressed.

**Comment by murlock1000** [comment]
The recent migration of element-web to the new rust crypto system without supporting [MSC3061](https://github.com/matrix-org/matrix-spec-proposals/pull/3061) has broken some of systems that relied on this feature. Specifically, the functionality where a bot would invite whitelisted users to a room and share room keys with them so they could see historic messages.

What is the current solution for an automated system that invites users to a room with existing messages and enables them to see historic messages now?

**Comment by mpeter50** [comment]
> If this works just fine, then I don't see why users can't be given the option. I think the "user is too stupid" mantra is usually taken too far

Because its not necessarily a stupid user. Maybe one with a very short attention span or one who really is in hurry, and does not read the option but just proceed out of habit. The former is not a rarity, to say the least. I have had a hard time believing this until I have seen this happen regularly with my eyes. Not in the context of Matrix, but with tech, the simpler kind. A lot of people also just dont read, but rather agonize, literally. And in either case I'm not speaking about the elderly.

Having it behind 4 button presses, plus a 10 second "thinking timer" like some android phones do with security settings would probably work fine, though.

> But tell me, why force encryption like Kopia also? Why not let us skip it?

You can skip it at room creation.

![image](https://github.com/element-hq/element-meta/assets/83356418/6913e45a-e75c-424f-8517-7b77d0434e32)

If your primary DM chat room's encryption breaks, you can create a new unencrypted one until you sort that out.
But a malicious homeserver may be able to get you into that state (e.g. by not forwarding to-device messages for you), so think twice before you do that.

> What is the current solution for an automated system that invites users to a room with existing messages and enables them to see historic messages now?

This is nothing official and it would be much better if Element employees could give advice.
But as a workaround you could use an element client with the old crypto to join that room.  The desktop app or a hosted web client, probably an older android app would work too.
This client would receive the keys, and hopefully it will be able to send them to your other clients, or upload it to key backup from where the others can download it.

---

I once again want to highlight that I am not an Element employee, I just wanted to give my 2 cents because for some issues I have already found a solution.

**Comment by jittygitty** [comment]
@mpeter50 Sorry for the confusion, you misunderstood my reply to @mrlogick because the entire section starting with "I really wanted to try out Kopia soon, and now I want to try bupstash.io also!" and ending with "Sorry I digressed" had nothing to do with Element chat at all, it was only about his "bupstash.io" project ( see https://github.com/andrewchambers/bupstash )

I knew that encryption in rooms is optional, I now no longer use it in some rooms which are hosted on my server (with encrypted drives) only and for which there's no federation and if only users on my server are allowed to join that room.

Anyway, I had already said that: "I'd agree such measures shouldn't be done "automatically or even too easily" such that it could be accidental, a good trade-off 'balance' should be attainable." So, of course I am perfectly fine to require a user to "TYPE" a long and exact phrase saying: "I Agree this is Dangerous and I insist on etc etc and know what I'm doing.."

Point was there's definitely ways like making people type something out which informs them that this is for advanced users and can be security risks involved etc, and such that nobody would be able to say they enabled it by "accident".

I'm just against policies that say, nope we're just not gonna give anyone such options, they'll have to go fork da code.

Anyway, I haven't had a chance yet to try this: https://github.com/element-hq/element-meta/issues/647#issuecomment-2200806424 
Because I'm still trying to convince my friend to reinstall Element and give it another try, hope I'll succeed convince him.
