### ISSUE TITLE
Remove unintentional pings 

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#886]
### Your use case

This is a meta issue that contains and concerns the work being undertaken to decide and implement the correct activity when a user's display name is used in message content. 

A users display name should not cause a ping (and today is does). Pings should always be intentional and obvious (maybe through pills).

---

Here are related bugs:
- https://github.com/vector-im/element-web/issues/6307

---

In the Delight team roadmap, "Remove unintentional pings" has 3 line items:
- [x] Remove the ping when a users display name is written in the timeline. Pings should only occur when a user is ""@"
- [ ] Reactions, poll messages, room events should not ping a user or leave a notification unread in their room list

**Comment by daniellekirkwood** [comment]
@clokep assigning you as you're currently the driver for this. Let me know if you need any product input.

**Comment by clokep** [comment]
There's a bunch of other cases document in the spec repo (or as part of MSCs):

* Replying to a message will re-issue pings from the initial message due to [fallback replies](https://spec.matrix.org/v1.5/client-server-api/#fallbacks-for-rich-replies). ([MSC2781](https://github.com/matrix-org/matrix-spec-proposals/pull/2781) proposes removing reply fallbacks which would solve this problem, although as noted in [MSC3676](https://github.com/matrix-org/matrix-spec-proposals/pull/3676) this may require landing [MSC3664](https://github.com/matrix-org/matrix-doc/pull/3664) in order to receive notifications of replies.)
* Each message edit will be re-evaluated for pings.
* Pings occurring [in spoiler contents](https://github.com/matrix-org/matrix-spec/issues/16) or [code blocks](https://github.com/matrix-org/matrix-spec/issues/15) are evaluated.
* If the [localpart of your Matrix ID is a common word](https://github.com/matrix-org/matrix-spec-proposals/issues/3011) then the `.m.rule.contains_user_name` rule matches frequently (e.g. Travis CI matching `@travis:example.com`).
* If the [localpart or display name of your Matrix ID matches the hostname](https://github.com/matrix-org/matrix-spec-proposals/issues/2735) (e.g. `@example:example.com` receives notifications whenever `@foo:example.com` is replied to).

If folks know of other cases I would like to hear about them!

**Comment by clokep** [comment]
See [MSC3952](https://github.com/matrix-org/matrix-spec-proposals/pull/3952).

**Comment by clokep** [comment]
I removed #901 from the description of this issue -- it is only vaguely related.

**Comment by clokep** [comment]
[MSC3952](https://github.com/matrix-org/matrix-spec-proposals/pull/3952) has been accepted into the spec, but there's some remaining work to get this in front of users:

* [ ] matrix-org/synapse#15487
* [ ] vector-im/element-web#25267

The bulk of that work is switching from unstable identifiers (`org.matrix.msc3952.*` to `m.*`) and enabling the features by default. As [mentioned in the MSC](https://github.com/matrix-org/matrix-spec-proposals/blob/clokep/intentional-mentions/proposals/3952-intentional-mentions.md#backwards-compatibility), backwards compatibility between clients and/or servers that are using the legacy rules vs. the new rules should not be an issue *most of the time*.

Note that [Element Web manually pulls push rules before each sync](https://github.com/matrix-org/matrix-js-sdk/blob/c2afc357b923f3d6a234a39f73541465d8dd7dda/src/sync.ts#L763) so it should immediately find out about these push rules when they're enabled on a homeserver. Additionally it [Element Web](https://github.com/matrix-org/matrix-js-sdk/blob/c2afc357b923f3d6a234a39f73541465d8dd7dda/src/client.ts#L9548-L9555) uses a server flag to decide whether to enable the feature or not, although I'm not really sure this is necessary.

I think this essentially means we can enable the backend and frontend completely separately.

**Comment by kerryarchibald** [comment]
@clokep / @daniellekirkwood do we care about backwards compatible support for the unstable identifiers? Ie do we need to support both `org.matrix.msc3952.*` and `m.*` on EW? AFAIK intentional mentions has not been released/available on mainline so the impact of abandoning the unstable identifier would be minimal.

**Comment by clokep** [comment]
> @clokep / @daniellekirkwood do we care about backwards compatible support for the unstable identifiers? Ie do we need to support both `org.matrix.msc3952.*` and `m.*` on EW? AFAIK intentional mentions has not been released/available on mainline so the impact of abandoning the unstable identifier would be minimal.

I was not planning to maintain any backwards compatibility on the server. I think impact is minimal and not worth it.

**Comment by daniellekirkwood** [comment]
Happy with that ☝️

**Comment by clokep** [comment]
@giomfo suggested that we likely want to do something to handle migrating of disabled push rules so that users don't just have mentions enabled by this work if they had previously disabled them. this sounds reasonable (although I have not yet investigated how hard it would be to do). From discussion we came up with:

* If `.m.rule.roomnotif` is disabled, then disable `.m.rule.is_room_mention`
* If both ` .m.rule.contains_display_name` and ` .m.rule.contains_user_name` are disabled, then disable ` .m.rule.is_user_mention`

For the second bullet, the thought was that if a single one of them is disabled the user is likely trying to get around the "unintentional" behavior we're fixing, but if they're *both* disabled then they really don't want mentions. This still might be overly aggressive, but a user can always re-enable it manually in the future.

@daniellekirkwood does this sound good to you? I can look at implementing before stabilizing.

**Comment by daniellekirkwood** [comment]
Yes, sounds good to me. 

Good catch both! Thank you

**Comment by clokep** [comment]
Cross-linking support for other projects (which isn't a blocker, but nice to have all in one spot):

* vector-im/element-android#8489
* vector-im/element-ios#7567
* ruma/ruma#1550 / ruma/ruma#1520

**Comment by clokep** [comment]
@daniellekirkwood Should we consider this done?

**Comment by daniellekirkwood** [comment]
> @daniellekirkwood Should we consider this done?

YES 🕺
